### ISSUE TITLE
Infinity Shard

### ISSUE THREAD

**Issue by Dimsumexpress** [Kashim1082/4.8-Bug-reports#45] opened 2019-10-07 02:44 UTC
- Hyperion shield does not disappear even after killing the generators
- he moves and follow you up to the stairway... supposedly just stay in the middle
- cd is too long , reset scroll does not work 
https://gyazo.com/8a972eb1bbffb88c01e42bf169e66792

**Comment by Kashim1082** [comment] 2019-10-25 15:34
Checked and it works just as intended.
CD scrolls will be fixed in a different issue.

**Closed as completed by Kashim1082** 2019-10-25 15:34 UTC
